### ISSUE TITLE
Connexion thruk ,etc

### ISSUE THREAD

**Issue by rabi29** [mgadi/naemonbox#23]
bonjour,

est ce normal que je dois fournir un couple login/password dans thruk alors que je me suis connecté sur naemonbox
Idem glpi, etc..

Fusion inventory ne se lance pas dans l interface naemonbox.
merci
a+

**Comment by mgadi** [comment]
Bonjour,

1 - L'authentification unique est une fonctionnalité qui n'est pas intégrée pour le moment. 
2 - Le menu Fusion Inventory est là, en prévision de faire du déploiement depuis la plateforme.

Voilà, Bon naemonbox !
