### ISSUE TITLE
creation host

### ISSUE THREAD

**Issue by rabi29** [mgadi/naemonbox#24]
bonjour,
a chaque fois que je cree un host windows j ai une erreur apres.
Error: Unable to locate host 'naemonbox-server' for service 'APT_Sofware_update'
Error: Could not register service (config file '/etc/naemon/conf.d/naemonbox-server.cfg', starting on line 134)
Error: Failed to locate host 'naemonbox-server' for hostgroup 'linux-servers'
Error: Bad member of hostgroup 'linux-servers' (config file '/etc/naemon/conf.d/naemonbox-server.cfg', starting on line 37).

Ce n est aps le cas avec pfsense qui sous freebsd.

et apres il n y a plus de /var/cache/naemon/live enfin plus de live (je n ai pas su defir que etait le type de live(fichier dossier exec service?)

a+

**Comment by mgadi** [comment]
Bonjour,

L'hôte naemonbox-server n'est pas présent. Ce qui n'est pas le cas des services et du groupe d'hôtes associés.

[naemonbox-server.pdf](https://github.com/mgadi/naemonbox/files/5088/naemonbox-server.pdf)
 

    cd /etc/naaemon/conf.d/
    wget --no-check-certificate -c https://github.com/mgadi/naemonbox/files/5088/naemonbox-server.pdf
    mv naemonbox-server.pdf naemonbox-server.cfg
    /etc/init.d/naemon configtest

Si pas d'erreurs 
 

     /etc/init.d/naemon start

Le fichier /var/cache/naemon/live est créé au lancement de naemon.

==========
Naemon charge tous les fichiers de ce répertoire /etc/naemon/conf.d/ . Je te propose  de séparer les objets, par exemple hostgroups.cfg, hosts.cfg,  servicegroups.cfg,  services.cfg , etc ...
Tu peux utiliser le template windows-server dans templates/hosts.cfg. Si tel est le cas, tu dois dé-commenter comme ci-dessous : 
![windowstemplate](https://cloud.githubusercontent.com/assets/4088423/10196879/5db23b76-6795-11e5-9f5b-a8d4b44b3611.PNG)
 

Pour aller plus loin, http://www.naemon.org/documentation/usersguide/objectdefinitions.html

**Comment by rabi29** [comment]
bonjour,
je me permet de rectifier mais naemonbox-server.cfg est cree a l installation.
j ai verifie et sauf erreur de ma part.

pour mes autre hosts:
j ai cree un repertoire perso dans le quel je mets mes hosts(  bureau.cfg, pfsense.cfg...)

c est vraiment a la creation du host windows que ca bug.

a+

**Comment by mgadi** [comment]
Bonjour Olivier,

Naemon fonctionne correctement (rien à voir avec Naemonbox et son installation)...

![image](https://cloud.githubusercontent.com/assets/4088423/10267188/6437bb9a-6a8a-11e5-8055-12a62ecc4189.png)
Soit tu fais comme dans la réponse qui t'ai donnée précédemment, tu peux aussi recréer l'hôte absent dans le fichier qui va bien, voire même supprimer les entrées qui font défaut (Naemon te donne la ligne 134 et 37) soit tu efface le fichier qui pose problème...

Bon Naemon !
