### ISSUE TITLE
Remonter information glpi

### ISSUE THREAD

**Issue by julienbenoist** [mgadi/naemonbox#26]
Bonjour,

J'aimerais savoir comment paramétrer naemon pour qu'il remonte les informations des problèmes ou warning vers glpi.

J'ai  vu qu'il y a les deux plugins notify-glpi mais je comprend pas comment les mettre en place sur les services déjà configurés, j'ai testé en ajoutant contact glpi sur un service mais aucune information remonte.
J'ai regardé la doc et j'ai pas réussi a trouver la procédure.

Merci

**Comment by mgadi** [comment]
Bonjour,

Quelle est la version de debian utilisée et architecture (32bit ou 64bit) ?
Quelle est la version de naemonbox utilisée pour l'install ?
Quel est le socle utilisé : machine physique vm, km, openvz, vagrant ?

Le paramétrage est déjà effectué. A la fin de l'installation vous devriez avoir un premier ticket de créé avec snmptrap-service comme ci-dessous :

![stacks-image-319559a-800x470](https://cloud.githubusercontent.com/assets/4088423/13277696/35e77c2e-dacb-11e5-9a7f-f410127e4d36.png)
![stacks-image-505733e-800x508](https://cloud.githubusercontent.com/assets/4088423/13277754/8cd764b8-dacb-11e5-8718-dfcfa9aaa12c.png)

Cordialement

**Comment by jbnitro** [comment]
Bonjour,

J'avais réussi a configurer les alertes par la suite en cherchant un peu

J'utilisais une vm debian 8.3 sur virtual box en 64bit avec la dernière version de naemonbox la 0.0.7
J'avais suivi votre tuto sur youtube et tout avait fonctionné après sans soucis.

**Comment by mgadi** [comment]
Bonjour,
Dans la configuration du service, rajouter le template **generic-active-service** .  Celui-ci permet d'envoyer une notification à GLPI, qui ensuite associe l'alerte reçu aux ticket. 

1. Le ticket n'existe pas, GLPI crée un ticket. 
2. Le ticket existe GLPI ajoute un suivi dans le ticket.

**Comment by mgadi** [comment]
Bonjour @julienbenoist, je peux clôturer le ticket  ?

**Comment by julienbenoist** [comment]
oui pas de soucis
