### ISSUE TITLE
Etat du service NAEMON KO

### ISSUE THREAD

**Issue by Naamo** [mgadi/naemonbox#29]
Bonjour, aprés modification de l'adresse ip par le fichier /etc/network/interfaces
![image](https://cloud.githubusercontent.com/assets/18165887/14665426/763416d2-06d3-11e6-81d0-ab732b8e0fc4.png)
et aprés redémarage complet de la machine, me voila avec le service NAEMON en statut KO au démarage...
![image](https://cloud.githubusercontent.com/assets/18165887/14665463/b42ffbfe-06d3-11e6-8283-7fbe5c6c87b1.png)
j'ai donc tenté de redémarrer le service:
_

> [root@naemonbox] ~ # service naemon restart
> Job for naemon.service failed. See 'systemctl status naemon.service' and 'journalctl -xn' for details.
> [root@naemonbox] ~ # service systemclt status
> ● systemclt.service
>    Loaded: not-found (Reason: No such file or directory)
>    Active: inactive (dead)
> 

_
l'acces web fonctionne mais j'ai des erreurs sur toutes les pages...
![image](https://cloud.githubusercontent.com/assets/18165887/14665685/1cdc1952-06d5-11e6-93dc-9bf1cdae1111.png)

Une idée...?

Merci bonne journée.

**Comment by mgadi** [comment]
Bonjour,

D'abord merci d’utiliser NaemonBox.

Pouvez-vous envoyer le résultat des commandes suivantes : 

```bash
tail -f /var/log/naemon/naemon.log
tail -f /var/log/naemon/livestatus.log
tail -f /var/log/naemon/thruk.log
```

**Comment by mgadi** [comment]
Bonsoir,

J'ai apporté une correction pour l'installation via github. 
Pour éviter une nouvelle installation, je propose : 

 ```bash
mv /etc/naemon/conf.d/localhost.cfg /etc/naemon/conf.d/naemonbox.cfg
sed -i "s/localhost/naemonbox/g" /etc/naemon/conf.d/naemonbox.cfg
rm /etc/naemon/conf.d/printer.cfg /etc/naemon/conf.d/switch.cfg /etc/naemon/conf.d/windows.cfg
service naemon start
 ```
Pour vérifier : 
```bash
naemonbox status
```
 @Naamo

**Comment by Naamo** [comment]
la commande tail -f ne donne rie, voila les commandes que j'ai faite :


[root@naemonbox] ~ # mv /etc/naemon/conf.d/localhost.cfg /etc/naemon/conf.d/naemonbox.cfg
mv: impossible d'évaluer « /etc/naemon/conf.d/localhost.cfg »: Aucun fichier ou dossier de ce type
[root@naemonbox] ~ # sed -i "s/localhost/naemonbox/g" /etc/naemon/conf.d/naemonbox.cfg
sed: impossible de lire /etc/naemon/conf.d/naemonbox.cfg: Aucun fichier ou dossier de ce type
[root@naemonbox] ~ # rm /etc/naemon/conf.d/printer.cfg /etc/naemon/conf.d/switch.cfg /etc/naemon/conf.d/windows.cfg
rm: impossible de supprimer « /etc/naemon/conf.d/printer.cfg »: Aucun fichier ou dossier de ce type
rm: impossible de supprimer « /etc/naemon/conf.d/switch.cfg »: Aucun fichier ou dossier de ce type
rm: impossible de supprimer « /etc/naemon/conf.d/windows.cfg »: Aucun fichier ou dossier de ce type
[root@naemonbox] ~ # service naemon start
Job for naemon.service failed. See 'systemctl status naemon.service' and 'journalctl -xn' for details.
[root@naemonbox] ~ # tail -f /var/log/naemon/naemon.log

^C
[root@naemonbox] ~ # naemon status

Naemon Core 1.0.3-source
Copyright (c) 2013-present Naemon Core Development Team and Community Contributors
Copyright (c) 2009-2013 Nagios Core Development Team and Community Contributors
Copyright (c) 1999-2009 Ethan Galstad
License: GPL

Website: http://www.naemon.org
Error: Cannot open main configuration file '/root/status' for reading!
Naemon 1.0.3-source starting... (PID=15654)
Local time is Fri Apr 22 10:25:41 CEST 2016
qh: Socket '/var/lib/naemon/naemon.qh' successfully initialized
qh: core query handler registered
nerd: Channel hostchecks registered successfully
nerd: Channel servicechecks registered successfully
nerd: Channel opathchecks registered successfully
nerd: Fully initialized and ready to rock!
wproc: Successfully registered manager as @wproc with query handler
wproc: Registry request: name=Core Worker 15658;pid=15658
wproc: Registry request: name=Core Worker 15657;pid=15657
wproc: Registry request: name=Core Worker 15656;pid=15656
wproc: Registry request: name=Core Worker 15655;pid=15655
Error: There are no services defined!
Error: There are no hosts defined!
Error: There are no contacts defined!
Error: Unable to write to check_result_path ('/var/lib/naemon/spool/checkresults') - No such file or directory
Warning: Nothing specified for illegal_macro_output_chars variable!
Bailing out due to errors encountered while running the pre-flight check.  Run Naemon from the command line with the -v option to verify your config before restarting. (PID=15654)
Event broker module 'NERD' deinitialized successfully.
[root@naemonbox] ~ # service naemon start
Job for naemon.service failed. See 'systemctl status naemon.service' and 'journalctl -xn' for details.
[root@naemonbox] ~ #

Voila mes fichier log de naemon, truk, livestatus https://www.dropbox.com/sh/3iy9exid4065kxd/AACl40SoXmdg2D-vbczUqwaQa?dl=0

**Comment by mgadi** [comment]
Bonjour,

![image](https://cloud.githubusercontent.com/assets/4088423/14763018/d161992c-0989-11e6-8cb4-092850da37e0.png)

Faire: 
 ```bash
naemon -v /etc/naemon/naemon.cfg
 ``` 
 Bon naemon !

**Comment by julienbenoist** [comment]
Oui j'ai résolu son problème cela venait d'une mauvaise définition d'un host dans hostgroup.cfg avec la commande service naemon configtest

**Comment by mgadi** [comment]
Bien joué, pb résolu.  Bon naemonbox !
