### ISSUE TITLE
Add non-free repository 

### ISSUE THREAD

**Issue by mgadi** [mgadi/naemonbox#3]
APT uses a file that lists the ‘sources’ from which packages can be obtained. This file is /etc/apt/sources.list.
The entries in this file normally should be :

```
deb http://ftp.fr.debian.org/debian/ wheezy main non-free contrib
deb-src http://ftp.fr.debian.org/debian/ wheezy main non-free contrib

deb http://security.debian.org/ wheezy/updates main contrib non-free
deb-src http://security.debian.org/ wheezy/updates main contrib non-free

# wheezy-updates, previously known as 'volatile'
deb http://ftp.fr.debian.org/debian/ wheezy-updates main contrib non-free
deb-src http://ftp.fr.debian.org/debian/ wheezy-updates main contrib non-free`
```

**Comment by mysteriousplanet** [comment]
Building 0.0.6-RC1 on a current Debain Wheezy (7.8) base build fails to add the non-free source as the contrib source isn't included as default.


You could probably replace 
sed -i "s/main contrib/main contrib non-free/g" /etc/apt/sources.list

with

sed -i "s/\(main.*\)/\1 non-free/g" /etc/apt/sources.list

I haven't checked if contrib is also required for build?

**Comment by mgadi** [comment]
Thank's for your comment. 
Could you Tell us how did your install the system.  
We recommand to install debian in expert mode like this : https://www.youtube.com/watch?v=lP_H3R9ft5o

**Comment by mysteriousplanet** [comment]
I wouldn't run the expert install unless the installer went badly wrong and failed to build using the minimal interface for some reason.  The only real thing I can think of benefit to doing that would be to set the LVM names a bit shorter.
I generally would run a zero-touch PXE net-boot install as I repeat install a lot and it saves me a lot of time. :)

**Comment by mgadi** [comment]
I also haven't checked if contrib is also required. Could you tell us if it work's in that case.

**Comment by mysteriousplanet** [comment]
I managed to get time to run another build without contrib and that went through fine on my VM test box with just main and non-free

**Comment by mgadi** [comment]
Thank's for the reply.
Enjoy Naemonbox
