### ISSUE TITLE
NaemonBox 0.0.7-RC6, Mettre à jour GLPI, découvert automatique du réseau.

### ISSUE THREAD

**Issue by ykasdi** [mgadi/naemonbox#31]
Bonjour,
Tout d’abord un grand merci pour votre effort.
J'ai installé NaemonBox 0.0.7-RC6, tout ça marche bien mais j'ai quelques questions :
1- Comment je peut faire le découvert automatique du réseau sur Naemon, et ajouter de Hosts automatiquement.
2-Est ce qu'il y a la possibilité de mettre à jour GLPI a la version 0.90.3.
3-Est ce qu'il y a la possibilité de charger les Ordinateurs de GLPI sur Naemon

Merci bien
Très cordialement

**Comment by mgadi** [comment]
Bonjour, 

Merci pour ce retour.

1 - Je vous livre le truc en l'état : 
 - Utiliser le script nmap2naemon qui se trouve dans le répertoire scripts de l'archive que vous avez décompressé pour l'installation, sinon  ici : https://github.com/mgadi/naemonbox/blob/master/scripts/nmap2naemon. 
 - Taper la commande ./nmap2nagios.sh  10.XX.XX.160/27 - ici le sous réseau est 10.XX.XX.160 et le masque 255.255.255.224 

![nmap2nagios](https://cloud.githubusercontent.com/assets/4088423/20008291/4419dd8a-a2a0-11e6-84a3-09a91b26e898.png)
- Remplacer l'adresse IP par le nom d'hôte dans le champ 'alias'  en utilisant le fichier 
« /tmp/nmaptonagios-$date$.cfg », 
- Placer ensuite le fichier modifié dans le dossier « /etc/naemon/conf.d/ ».
- Appliquer les modifications depuis l’interface de configuration de NAEMON en http : 

1)	Config tool
2)	Apply
3)	Check your configuration changes (vérifie la présence d'erreurs de configuration)
4)	Reload your monitoring core (relance naemon avec la nouvell configuration)

![appliquer-conf-naemon](https://cloud.githubusercontent.com/assets/4088423/20008996/0722f706-a2a3-11e6-8ab4-655993167663.png)

2 - Il est prévu de monter en version GLPI dans la prochaine mouture. Par contre, si vous faites la mise à jour vous-même, vous perdrez l'automatisation des tickets générés par les alarmes de naemon!
3 - C'est à l'étude .

Bien à vous

**Comment by ykasdi** [comment]
Merci bien pour votre réponse .. j'attends la prochaine version pour le nouveau GLPI .

Merci bien
Très cordialement
