### ISSUE TITLE
Erreur commande checkMeM NRPE

### ISSUE THREAD

**Issue by ykasdi** [mgadi/naemonbox#32]
Bonjour, 
je suis entrain de tester la solution Neamonbox, Merci pour vos efforts. 

j'ai un problème quant j’exécute la commande CheckMeM 
`/usr/lib/nagios/plugins/check_nrpe -H 192.168.1.200 -p 5666 -c CheckMEM -a MaxWarn=80% MaxCrit=90% ShowAll type=physical `
j'ai la résultat suivante : 
`Exception processing request: Request contained arguments (not currently allowed, check the allow arguments option).`

Alors j'ai un problème dans les arguments donc j'ai essayé de supprimer "-a" et j'ai exécuté la commande.
`/usr/lib/nagios/plugins/check_nrpe -H 192.168.1.200 -p 5666 -c CheckMEM MaxWarn=80% MaxCrit=90% ShowAll type=physical`

Après ça j'ai obtenu la résultat suivante : 
`OK: committed: Total: 7.794GB - Used: 4.345GB (55%) - Free: 3.448GB (44%), physical: Total: 3.898GB - Used: 3.008GB (77%) - Free: 911.516MB (22%)|'committed'=4.34513GB;6.2349;7.01426;0;7.79362 'committed %'=56%;80;90;0;100 'physical'=3.00754GB;3.11816;3.50793;0;3.8977 'physical %'=77%;80;90;0;100`
je ne sais pas pourquoi la commande ne prend pas en considération les argument -a, sachant que je voulais afficher juste la mémoire physique. 

Merci bien .

**Comment by ykasdi** [comment]
J'ai résolut le probléme 
j'ai ajouter la ligne 
[/settings/NRPE/server]
`allow arguments= true`
dans le fichier de configuration NSClient++ 
Merci bien .

**Comment by mgadi** [comment]
Bonjour,

Merci pour votre retour. 

Et oui ça arrive, le fait de se poser la bonne question peut permettre de trouver soi-même la réponse.

Bon naemonbox !
